### ISSUE TITLE
Refused to execute script bundle from its MIME type ('') is not executable.

### ISSUE THREAD

**Issue by ysfzrn** [vincentriemer/react-native-dom#100]
When I working with DEV mode, this library works succesfully but I want to serve production mode. I followed all instructions. I created dist file. But when I serve , I encountering this error

`Refused to execute script from 'http://localhost:5000/entry.bundle?platform=dom&dev=true&hot=true' because its MIME type ('text/plain') is not executable..`

How can I deploy my project and serve production mode ?

**Comment by dutzi** [comment]
In your production server just set the mime type for those files to text/javascript

**Comment by ysfzrn** [comment]
thanks, I didn't know
