### ISSUE TITLE
Demos/examples not working on iOS/Safari

### ISSUE THREAD

**Issue by holmesal** [vincentriemer/react-native-dom#20]
This project is so cool! Nice work!

The examples only work on my Mac - when I try to visit rntester.now.sh on my phone (Safari on iPhone 6), I see the following errors in the console:

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/1147390/40216432-8a6f61f0-5aa1-11e8-913f-44d51ded4d6c.png">

**Comment by vincentriemer** [comment]
Are you running iOS 11.2? This is likely due to a bug they had with WebAssembly when they were mitigating the spectre vulnerabilities and got fixed in 11.3.

**Comment by vincentriemer** [comment]
Since this is a known issue that we can't really do anything about, I'm going to close this. You can read more about the issue causing this here: https://github.com/kripken/emscripten/issues/6042
