### ISSUE TITLE
Flex layout not consistent with native device layouts

### ISSUE THREAD

**Issue by darthtrevino** [vincentriemer/react-native-dom#28]
I'm aware of the "it's not ready for production" caveat, but I wanted to kick the tires and play with this lib a bit. I added react-native-dom to an application I'm working on, and I'm seeing some issues with layout. The layout in RNDom isn't matching iOS or Android, so I'm guessing there's something janky in how Yoga is being applied.

In this example, each row has two children, one for the title and one for this magnitude bar. The title is `flex: 2` and the magbar is `flex: 1`. The RNDom version has inconsistent sizings from row-to-row.

![Layout on iOS](https://user-images.githubusercontent.com/113544/40248053-795ad674-5a83-11e8-86cb-d3ef86c7696a.png)
![Layout on react-native-dom](https://user-images.githubusercontent.com/113544/40248054-7974a482-5a83-11e8-8ad0-db36ec8b7e92.png)

**Comment by motiz88** [comment]
@darthtrevino - any chance you could provide a code snippet?

**Comment by vincentriemer** [comment]
Yeah, in order to triage this we're going to need a reproduction of the bug. If you can create a repo that showcases it that would be great!

**Comment by darthtrevino** [comment]
https://github.com/darthtrevino/react-native-dom-layout-issue

![screen shot 2018-05-22 at 1 11 29 pm](https://user-images.githubusercontent.com/113544/40387501-ce346516-5dc1-11e8-9003-cc8db455bd17.png)
