### ISSUE TITLE
ENOENT: no such file or directory, open './dom/dist/entry.bundle'

### ISSUE THREAD

**Issue by thebetterjort** [vincentriemer/react-native-dom#50]
```
react-native bundle \
>   --config $(pwd)/rn-cli.config.js \
>   --dev false \
>   --entry-file ./dom/entry.js \
>   --platform dom \
>   --bundle-output ./dom/dist/entry.bundle \
>   --assets-dest ./dom/dist

```

I fixed this error by creating the dom folder by hand. Do I need to run this command with sudo?

**Comment by hawkrives** [comment]
@thebetterjort What error are you getting, exactly?

**Comment by thebetterjort** [comment]
Loading dependency graph, done.
bundle: Writing bundle output to: ./dom/dist/bootstrap.bundle

ENOENT: no such file or directory, open './dom/dist/bootstrap.bundle'

On Linux (4.13.0.43-generic), Ubuntu 17.10, node v8.11.2

**Comment by vincentriemer** [comment]
Whoops yeah sorry I forgot to add the step where you create the dist folder (‘mkdir -p ./dom/dist’) before you run the bundle commands. I’ll try to get to it soon or someone else can create PR with the doc addition.

**Comment by thebetterjort** [comment]
I ran the following command inside of my project folder:

mkdir dom

**Comment by thebetterjort** [comment]
https://github.com/vincentriemer/react-native-dom/pull/51
