### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by kross77** [vincentriemer/react-native-dom#54]
Hello, i'm trying to run my react-native-scripts project and have the issues.
First, the command run the, (review the node package)
`react-native run-dom --port=19000`, but he don't recognize this option
But i can run the packager on 8081 port

Second, i'm not sure that is related with first issue. When i'm starting 
i've the error:
` bundling failed: Error: Unable to resolve module "./BarCodeScanner" from "/node_modules/expo/src/Expo.js": The module "./BarCodeScanner" could not be found from "node_modules/expo/src/Expo.js". Indeed, none of these files exist: `
In Expo BarCodeScanner we have the file with extension BarCodeScanner.web.js, so it is good to support compilation for this one.

**Comment by vincentriemer** [comment]
It's actually the other way around, this project can technically "support" expo but expo does not support the `dom` platform.

**Comment by kross77** [comment]
Could you say more about technically support?

**Comment by vincentriemer** [comment]
Expo needs to port its native modules to rndom, and since rndom has a
native module system it is possible to do. Porting the expo modules to the
web is out of the scope of this project.

**Comment by kross77** [comment]
@vincentriemer But expo has support for the web platform, what i'm request, not support all features from framework, but do the demo what is run with expo framework. For my point, now it is supporting the compiling the files with extension .web.js, and i can't find where i can do it in your code, may be you show the place or file where i can add this support.

**Comment by vincentriemer** [comment]
This project uses `dom.js` not `web.js` because platform-specific code written for RNW is incompatible with RND

**Comment by kross77** [comment]
Thanks for reply.
