### ISSUE TITLE
Map .dom.js to .web.js

### ISSUE THREAD

**Issue by patlux** [vincentriemer/react-native-dom#66]
Hello,

I know RNDom is incompatible to RNW, but for the most of the project files in my project I don't have a difference between DOM and WEB. Is there a configuration way (maybe in the rn-cli.config.js?) to take the `.web.js` file if there is no `.dom.js`?

In the meantime I have to duplicate all `.web.js` files to `.dom.js` files.

Thank you

**Comment by piranna** [comment]
I believe the same, probably `*.web.js` could be a sane fallback in most cases when a `*.dom.js` is not available...

**Comment by robertherber** [comment]
Agree. This is needed to use third-party libs that have web support as well, for example react-native-paper.

**Comment by salvariable** [comment]
@robertherber which UI lib are you using?

**Comment by robertherber** [comment]
> @robertherber which UI lib are you using?

The one I mentioned - react-native-paper. I did however submit a [pull request](https://github.com/callstack/react-native-paper/pull/744) to fix the issue for that particular lib. But I still think this is a good idea for RND - it's better to at least try with a .web.js as fallback if there is no .dom.js.

**Comment by dai-shi** [comment]
I tried doing this naively in my project: https://github.com/dai-shi/react-native-dom-expo
The result is not very successfull because some of *.web.js depend on react-dom.
It's maybe only because of Expo, which includes a bunch of packages by default.
