### ISSUE TITLE
Live reloading

### ISSUE THREAD

**Issue by luandro** [vincentriemer/react-native-dom#69]
First congratulations, this is an amazing project. Is there a way to live or hot reload the dom app in development?

**Comment by vincentriemer** [comment]
I haven't put much focus on it, but there is a runtime flag you can toggle in your `bootstrap.js` file that's generated for you: https://github.com/vincentriemer/react-native-dom/blob/e9edcbbc21d81a7dfde0f15033b78a4effb25b52/packages/react-native-dom/local-cli/generator-dom/templates/bootstrap.js#L8
