### ISSUE TITLE
TouchableOpacity Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by 25juan** [vincentriemer/react-native-dom#77]
package.json:
    
    "react-native": "0.57.0",
    "react-native-dom": "0.4.1",

TouchableOpacity component error。i don't kown how to deal it

error code:

![image](https://user-images.githubusercontent.com/14308183/45802118-74a1de80-bce8-11e8-9426-20de28f31dda.png)

**Comment by vincentriemer** [comment]
`TouchableOpacity` isn't specifically implemented in RNDom, it simply uses the exact same JS code from the RN core, so this is likely either a bug in your code or the RN core.
