### ISSUE TITLE
Integration with React Developer Tools

### ISSUE THREAD

**Issue by tbergman** [vincentriemer/react-native-dom#81]
Hi Vincent,
Thanks a lot for this incredible project!
What needs to be done to view the React component tree in one of the following and how can I help? :
- Standalone React Developer Tools / React Native Debugger
- React Devtools Chrome extension

**Comment by vincentriemer** [comment]
The standalone react developer tools already work! It's not documented, but if you add `?devtools` to the end of your development url and it will activate the connection between devtools.

**Comment by tbergman** [comment]
Great, thanks!
I’ve sent you a PR with a suggested documentation.
